languageCode = "en"
languageName = "English"
weight = 1
title = "Blowfish"

[params]
  displayName = "English"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/Rollens_Logo.png"
  description = "A powerful, lightweight theme for Hugo."

[params.author]
  name = "Rollens"
  email = "content.me@rollens.life"
  image = "img/Rollens_Logo.png"
  headline = "Travel, Adventure"
  bio = "Aussie life."
  links = [
    { x-twitter = "https://twitter.com/burufugu" },
    { github = "https://github.com/nunocoracao/blowfish" },
  ]