languageCode = "zh-Hant"
languageName = "繁體中文"
weight = 4
title = "Blowfish"

[params]
  displayName = "繁體中文"
  isoCode = "zh-Hant"
  rtl = false
  dateFormat = "2006-01-02"
  logo = "img/blowfish_logo_transparent.png"
  description = "一個強大、輕量級的Hugo主題"

[params.author]
  name = "Rollens"
  image = "img/blowfish_logo.png"
  headline = "一個強大、輕量級的Hugo主題"
  bio = "一個強大、輕量級的Hugo主題"
  links = [
    { threads = "https://www.threads.com/@rs_tt.ke?igshid=NTc4MTIwNjQ2YQ==" },
    { github = "https://github.com/rollens" },
  ]